### ISSUE TITLE
Site Refusing to pull all base styles

### ISSUE THREAD

**Issue by sputter1302** [luciddesign/bootstrapify#235] opened 2015-07-09 15:14 UTC
It still pulls my custom stylesheet, but the base stylesheet compiles to contain only this:

Invalid CSS after "Liquid error:": expected pseudoclass or pseudoelement, was " invalid integer"
Syntax error: Invalid CSS after "Liquid error:": expected pseudoclass or pseudoelement, was " invalid integer"
        on line 9266 of an unknown file

**Comment by pushrax** [comment] 2015-07-09 20:19
Duplicate of https://github.com/luciddesign/bootstrapify/issues/234

@stewartknapman note that this *does* mean there is a range somewhere with an invalid string argument (such as `""` or `"asdf"`). The old behaviour was to ignore those invalid arguments and use 0 as the range limit, since in Ruby `to_i` on random strings returns 0. You may or may not care about fixing it.

**Comment by sputter1302** [comment] 2015-07-09 20:35
Thanks!

**Closed** 2015-07-09 20:36 UTC
